version: "3.8"

networks:
  app_net:
    driver: bridge

volumes:
  mongo_data:

services:
  web:
    build: ./src
    ports:
      - 80:5000
    networks:
      - app_net
    depends_on:
      - mongodb
    environment:
      MONGODB_DB: ${MONGODB_DB}
      MONGODB_HOST: ${MONGODB_HOST}
      MONGODB_PORT: ${MONGODB_PORT}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}

  mongodb:
    image: mongo:${MONGO_VERSION}
    networks:
      - app_net
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD:  ${MONGODB_PASSWORD}
